### ISSUE TITLE
Can't open qvf-file

### ISSUE THREAD

**Issue by mruehl** [rvspt/D3DynamicTreeLayout-QS#1]
I can't open the qvf-file in Version 2.2.4.
So I can't check, why my hierarchy doesn't work.

**Comment by rvspt** [comment]
Sorry, QVF was created using Version 3. The extension works on previous
versions though.

**Comment by mruehl** [comment]
Thanks for the great extension! It works for me now even in 2.2.4. I had a problem with the depth because I didn't create it within hieararchy-load.
