### ISSUE TITLE
Linking table to data model

### ISSUE THREAD

**Issue by jveldhoen** [rvspt/D3DynamicTreeLayout-QS#2]
Hi Renato,

Thanks for this great extension. I am using this to visualize a value driver tree. Unfortunately it seems I cannot link the table to the rest of my data model. As soon as I link the hierarchy table to my fact table, the visualization disappears. This is also the case with no selections. Any thoughts on this??

Regards,

Jeroen

PS: Saw your bio pic, did you enjoy Amsterdam? :)

**Comment by rvspt** [comment]
As we discussed on phone and you managed to solve, I will close the issue.

Btw, yep, Amsterdam was a nice stay!
