### ISSUE TITLE
The extension doesn't work with objects > 1000 rows

### ISSUE THREAD

**Issue by dedpnd** [rvspt/D3DynamicTreeLayout-QS#3]
Hi, @rvspt thx for extension.
I have a table in which more than 1000 records and when loading the extension does not show anything.
I have read that this limit "Sense" to objects in 1000 rows.
Any idea how to solve it ?

**Comment by rvspt** [comment]
Hello dedpnd, I opted to keep the 1000 rows limitation as I thought it would be too much information to render and make the object too confusing to read.

To solve this I could recommend 2 possible solutions:

1.  Work with the getData method to page the results - http://help.qlik.com/en-US/sense-developer/3.1/Subsystems/APIs/Content/BackendAPI/getdata-method.htm -  You can find a working example on @mindspank GoogleMaps Extension at https://github.com/mindspank/GoogleMaps-Sense/blob/master/GoogleMaps-Sense.js

2. Add a calculation condition to this extension to avoid rendering before it's in fact understandable to read. This is something I might add in the future, but I have no time available for a quick-fix these next days.

**Comment by rvspt** [comment]
I've implemented option 2 on the extension.
