### ISSUE TITLE
Problem to use the extension in qlik sense

### ISSUE THREAD

**Issue by ndima31** [rvspt/D3DynamicTreeLayout-QS#5]
Hello,
i'm trying to use the extension in QlikSense, i import it in Qlik Sense, i can see it in my panel of extensions. but when i drag and drop the extension into the sheet, i have a message that ask me that i have to select node. like this 
![image](https://user-images.githubusercontent.com/29305550/27083528-28cea3f6-5049-11e7-8741-3ce2d32279c7.png)
i don't understand where i have to défine the nodes etc... 
thanks for your attention

**Comment by rvspt** [comment]
Hello,

This extension needs to have the parameters specified directly in the extension's properties on the right side of your screen. Drag'n'drop is not available at this time. Sorry for the inconvenience. Who knows in a future one, the tutorial can coexist with the drag'n'drop :)
