### ISSUE TITLE
Does not render in Sense Sept 2017

### ISSUE THREAD

**Issue by mountaindude** [rvspt/D3DynamicTreeLayout-QS#6]
Trying to use the extension with Sense September 2017 version.

Using a very basic load script from the Sense help pages:

TreeView:
Hierarchy(NodeID, ParentID, NodeName, ParentName, NodeName, PathName, '\', Depth) LOAD * inline [
NodeID, ParentID, NodeName
1, 4, London
2, 3, Munich
3, 5, Germany
4, 5, UK
5, , Europe
];

This gives me a table like this:

![bigquery_360_v2_beta_dev___sheets_-_qlik_sense](https://user-images.githubusercontent.com/1029262/30965362-791af94e-a455-11e7-8f83-96de01a196ac.png)

But the extension does not recognise anything I enter in the Node name property:

![bigquery_360_v2_beta_dev___sheets_-_qlik_sense](https://user-images.githubusercontent.com/1029262/30965436-b836e002-a455-11e7-8b94-2c6c2a0bce0a.png)

Am I missing something in the formatting of the data, or is it a bug?

**Comment by mountaindude** [comment]
Looks like 
					list_nodeName:{
						ref: "qListObjectDef.qDef.qFieldDefs.0",
						label: "Node Name",
						type: "string",
						expression: ""
					},//qListObjectDef.qDef.qFieldDefs

is causing this. 

Removing that, and re-instating the nodeName property makes the extension tick again.

**Comment by pertjo** [comment]
mountaindude

How do i re-instating the nodeName property? 

im new to extensions and i would be really happy if you explained in more detail of how i should do. 
Because when i delete "list_nodeName" the hole textbox disappear

**Comment by rvspt** [comment]
Updated the extension. v1.3.1 should cover the issue.
