### ISSUE TITLE
Rejecting Node Name

### ISSUE THREAD

**Issue by mnyting** [rvspt/D3DynamicTreeLayout-QS#9]
**Node Name** stays red even if the field exists and is spelled properly, and extension would not render. Node Depth, Node Id and Parent Node Id turn green as soon as they are filled out. What am I doing wrong? QVD sourced table maintains the parent-child ids even across a flattened dimensional hierarchy, created by using the Qlik Hierarchy function.

**Comment by SyedAlamdar** [comment]
Having the same exact issue. 
![image](https://user-images.githubusercontent.com/34166232/33490717-111525d2-d686-11e7-83f2-08d5c3344e21.png)
![image](https://user-images.githubusercontent.com/34166232/33490772-312c6286-d686-11e7-8345-8b9e667d2684.png)
Not sure why but I was really looking forward to use this and I am stuck for reasons unknown. Any help will be appreciated.

**Comment by caiocaminoski** [comment]
Same problem happening here!

**Comment by amien90** [comment]
Same here

**Comment by fcorivasd** [comment]
Hi,

Go to the file extension-properties.js and change these items from the line 48.

					list_nodeName:{
						ref: "qListObjectDef.qDef.qFieldDefs.0",
						label: "Node Name",
						type: "string",
						expression: ""
					},//qListObjectDef.qDef.qFieldDefs
					nodeName: {
						ref: "properties.treeStructure.nodeName",
						//ref: "qListObjectDef.qDef.qFieldDefs.0",
						label: "Hidden Node Name",
						type: "string",
						expression: "",
						show: true
					},//treeConfiguration.items.treeStructure.items.nodeName

Then, in the properties of the object in qliksense, you will have another field to put information. Just include the NodeName and that's it.

I hope you can resolve (temporarily) this problem.

Regards

Francisco Rivas

**Comment by amien90** [comment]
Thanks .. works

**Comment by madhaviGPC** [comment]
Extension is able to render after the change, but still unable to make selection. What else can I change to make the selections in the nodes

**Comment by aniletnirmal** [comment]
facing Same issue even after adding the code.

**Comment by rvspt** [comment]
Updated the extension. v1.3.1 should cover the issue.
